update desp set modalidade_licitacao_codigo = trim(modalidade_licitacao_codigo);
update desp set funcao_codigo = trim(funcao_codigo);
update desp set mes = trim(mes);

update desp set orgao_codigo = '56' where orgao_codigo ='26';
update desp set orgao_codigo = '43' where orgao_codigo ='13';
update desp set orgao_codigo = '62' where orgao_codigo ='32';
update desp set orgao_codigo = '59' where orgao_codigo ='29';
update desp set orgao_codigo = '51' where orgao_codigo ='21';
update desp set orgao_codigo = '45' where orgao_codigo ='15';
update desp set orgao_codigo = '50' where orgao_codigo ='20';
update desp set orgao_codigo = '64' where orgao_codigo ='34';
update desp set orgao_codigo = '53' where orgao_codigo ='23';
update desp set orgao_codigo = '49' where orgao_codigo ='19';
update desp set orgao_codigo = '69' where orgao_codigo ='39';
update desp set orgao_codigo = '61' where orgao_codigo ='31';
update desp set orgao_codigo = '48' where orgao_codigo ='18';

update receitas set orgao_codigo = '56' where orgao_codigo ='26';
update receitas set orgao_codigo = '43' where orgao_codigo ='13';
update receitas set orgao_codigo = '62' where orgao_codigo ='32';
update receitas set orgao_codigo = '59' where orgao_codigo ='29';
update receitas set orgao_codigo = '51' where orgao_codigo ='21';
update receitas set orgao_codigo = '45' where orgao_codigo ='15';
update receitas set orgao_codigo = '50' where orgao_codigo ='20';
update receitas set orgao_codigo = '64' where orgao_codigo ='34';
update receitas set orgao_codigo = '53' where orgao_codigo ='23';
update receitas set orgao_codigo = '49' where orgao_codigo ='19';
update receitas set orgao_codigo = '69' where orgao_codigo ='39';
update receitas set orgao_codigo = '61' where orgao_codigo ='31';